;(function(){
var f;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ea(a,b){null!=a&&this.append.apply(this,arguments)}ea.prototype.pa="";ea.prototype.append=function(a,b,c){this.pa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.pa+=arguments[d];return this};ea.prototype.toString=function(){return this.pa};var fa=null;function ga(){return new q(null,5,[ha,!0,ia,!0,ja,!1,la,!1,ma,null],null)}function r(a){return null!=a&&!1!==a}function na(a){return r(a)?!1:!0}function s(a,b){return a[n(null==b?null:b)]?!0:a._?!0:v?!1:null}function oa(a){return null==a?null:a.constructor}function w(a,b){var c=oa(b),c=r(r(c)?c.nb:c)?c.mb:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function pa(a){var b=a.mb;return r(b)?b:""+x(a)}
function y(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}var qa={},ra={};function z(a){if(a?a.F:a)return a.F(a);var b;b=z[n(null==a?null:a)];if(!b&&(b=z._,!b))throw w("ICounted.-count",a);return b.call(null,a)}function sa(a,b){if(a?a.B:a)return a.B(a,b);var c;c=sa[n(null==a?null:a)];if(!c&&(c=sa._,!c))throw w("ICollection.-conj",a);return c.call(null,a,b)}
var ta={},A=function(){function a(a,b,c){if(a?a.S:a)return a.S(a,b,c);var h;h=A[n(null==a?null:a)];if(!h&&(h=A._,!h))throw w("IIndexed.-nth",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.w:a)return a.w(a,b);var c;c=A[n(null==a?null:a)];if(!c&&(c=A._,!c))throw w("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,g){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),
ua={};function C(a){if(a?a.P:a)return a.P(a);var b;b=C[n(null==a?null:a)];if(!b&&(b=C._,!b))throw w("ISeq.-first",a);return b.call(null,a)}function E(a){if(a?a.Q:a)return a.Q(a);var b;b=E[n(null==a?null:a)];if(!b&&(b=E._,!b))throw w("ISeq.-rest",a);return b.call(null,a)}
var va={},F=function(){function a(a,b,c){if(a?a.M:a)return a.M(a,b,c);var h;h=F[n(null==a?null:a)];if(!h&&(h=F._,!h))throw w("ILookup.-lookup",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.L:a)return a.L(a,b);var c;c=F[n(null==a?null:a)];if(!c&&(c=F._,!c))throw w("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function wa(a,b,c){if(a?a.qa:a)return a.qa(a,b,c);var d;d=wa[n(null==a?null:a)];if(!d&&(d=wa._,!d))throw w("IAssociative.-assoc",a);return d.call(null,a,b,c)}var xa={},ya={};function za(a){if(a?a.Ua:a)return a.Ua();var b;b=za[n(null==a?null:a)];if(!b&&(b=za._,!b))throw w("IMapEntry.-key",a);return b.call(null,a)}function Ba(a){if(a?a.Va:a)return a.Va();var b;b=Ba[n(null==a?null:a)];if(!b&&(b=Ba._,!b))throw w("IMapEntry.-val",a);return b.call(null,a)}var Ca={};
function Da(a,b,c){if(a?a.Ra:a)return a.Ra(a,b,c);var d;d=Da[n(null==a?null:a)];if(!d&&(d=Da._,!d))throw w("IVector.-assoc-n",a);return d.call(null,a,b,c)}function G(a){if(a?a.ab:a)return a.state;var b;b=G[n(null==a?null:a)];if(!b&&(b=G._,!b))throw w("IDeref.-deref",a);return b.call(null,a)}var Ea={};function Fa(a){if(a?a.G:a)return a.G(a);var b;b=Fa[n(null==a?null:a)];if(!b&&(b=Fa._,!b))throw w("IMeta.-meta",a);return b.call(null,a)}
function Ga(a,b){if(a?a.I:a)return a.I(a,b);var c;c=Ga[n(null==a?null:a)];if(!c&&(c=Ga._,!c))throw w("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var Ha={},Ia=function(){function a(a,b,c){if(a?a.O:a)return a.O(a,b,c);var h;h=Ia[n(null==a?null:a)];if(!h&&(h=Ia._,!h))throw w("IReduce.-reduce",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.N:a)return a.N(a,b);var c;c=Ia[n(null==a?null:a)];if(!c&&(c=Ia._,!c))throw w("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Ja(a,b){if(a?a.s:a)return a.s(a,b);var c;c=Ja[n(null==a?null:a)];if(!c&&(c=Ja._,!c))throw w("IEquiv.-equiv",a);return c.call(null,a,b)}function Ka(a){if(a?a.v:a)return a.v(a);var b;b=Ka[n(null==a?null:a)];if(!b&&(b=Ka._,!b))throw w("IHash.-hash",a);return b.call(null,a)}var La={};function Ma(a){if(a?a.C:a)return a.C(a);var b;b=Ma[n(null==a?null:a)];if(!b&&(b=Ma._,!b))throw w("ISeqable.-seq",a);return b.call(null,a)}var Na={};
function H(a,b){if(a?a.Ya:a)return a.Ya(0,b);var c;c=H[n(null==a?null:a)];if(!c&&(c=H._,!c))throw w("IWriter.-write",a);return c.call(null,a,b)}var Oa={};function Pa(a,b,c){if(a?a.t:a)return a.t(a,b,c);var d;d=Pa[n(null==a?null:a)];if(!d&&(d=Pa._,!d))throw w("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function Qa(a,b,c){if(a?a.Xa:a)return a.Xa(0,b,c);var d;d=Qa[n(null==a?null:a)];if(!d&&(d=Qa._,!d))throw w("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function Ra(a){if(a?a.xa:a)return a.xa(a);var b;b=Ra[n(null==a?null:a)];if(!b&&(b=Ra._,!b))throw w("IEditableCollection.-as-transient",a);return b.call(null,a)}function Sa(a,b){if(a?a.ya:a)return a.ya(a,b);var c;c=Sa[n(null==a?null:a)];if(!c&&(c=Sa._,!c))throw w("ITransientCollection.-conj!",a);return c.call(null,a,b)}function Ta(a){if(a?a.za:a)return a.za(a);var b;b=Ta[n(null==a?null:a)];if(!b&&(b=Ta._,!b))throw w("ITransientCollection.-persistent!",a);return b.call(null,a)}
function Ua(a,b,c){if(a?a.sa:a)return a.sa(a,b,c);var d;d=Ua[n(null==a?null:a)];if(!d&&(d=Ua._,!d))throw w("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function Va(a,b,c){if(a?a.Wa:a)return a.Wa(0,b,c);var d;d=Va[n(null==a?null:a)];if(!d&&(d=Va._,!d))throw w("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function Wa(a){if(a?a.Sa:a)return a.Sa();var b;b=Wa[n(null==a?null:a)];if(!b&&(b=Wa._,!b))throw w("IChunk.-drop-first",a);return b.call(null,a)}
function Xa(a){if(a?a.Ca:a)return a.Ca(a);var b;b=Xa[n(null==a?null:a)];if(!b&&(b=Xa._,!b))throw w("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function Ya(a){if(a?a.Da:a)return a.Da(a);var b;b=Ya[n(null==a?null:a)];if(!b&&(b=Ya._,!b))throw w("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function Za(a){if(a?a.Ba:a)return a.Ba(a);var b;b=Za[n(null==a?null:a)];if(!b&&(b=Za._,!b))throw w("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function $a(a){this.ob=a;this.n=0;this.f=1073741824}$a.prototype.Ya=function(a,b){return this.ob.append(b)};function I(a){var b=new ea;a.t(null,new $a(b),ga());return""+x(b)}function ab(a,b){if(r(K.a?K.a(a,b):K.call(null,a,b)))return 0;var c=na(a.J);if(r(c?b.J:c))return-1;if(r(a.J)){if(na(b.J))return 1;c=bb.a?bb.a(a.J,b.J):bb.call(null,a.J,b.J);return 0===c?bb.a?bb.a(a.name,b.name):bb.call(null,a.name,b.name):c}return cb?bb.a?bb.a(a.name,b.name):bb.call(null,a.name,b.name):null}
function db(a,b,c,d,e){this.J=a;this.name=b;this.ha=c;this.ia=d;this.oa=e;this.f=2154168321;this.n=4096}f=db.prototype;f.t=function(a,b){return H(b,this.ha)};f.v=function(){var a=this.ia;return null!=a?a:this.ia=a=eb.a?eb.a(L.d?L.d(this.J):L.call(null,this.J),L.d?L.d(this.name):L.call(null,this.name)):eb.call(null,L.d?L.d(this.J):L.call(null,this.J),L.d?L.d(this.name):L.call(null,this.name))};f.I=function(a,b){return new db(this.J,this.name,this.ha,this.ia,b)};f.G=function(){return this.oa};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return F.c(c,this,null);case 3:return F.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return F.c(a,this,null)};f.a=function(a,b){return F.c(a,this,b)};f.s=function(a,b){return b instanceof db?this.ha===b.ha:!1};f.toString=function(){return this.ha};
function M(a){if(null==a)return null;if(a&&(a.f&8388608||a.wb))return a.C(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new fb(a,0);if(s(La,a))return Ma(a);if(v)throw Error([x(a),x("is not ISeqable")].join(""));return null}function N(a){if(null==a)return null;if(a&&(a.f&64||a.ra))return a.P(null);a=M(a);return null==a?null:C(a)}function P(a){return null!=a?a&&(a.f&64||a.ra)?a.Q(null):(a=M(a))?E(a):Q:Q}
function S(a){return null==a?null:a&&(a.f&128||a.vb)?a.Y(null):M(P(a))}
var K=function(){function a(a,b){return null==a?null==b:a===b||Ja(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=T(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(S(e))a=d,d=N(e),e=S(e);else return b.a(d,N(e));else return!1}a.o=2;a.l=function(a){var b=N(a);a=S(a);var d=N(a);a=P(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,g){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);
default:return c.g(b,e,T(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.o=2;b.l=c.l;b.d=function(){return!0};b.a=a;b.g=c.g;return b}();ra["null"]=!0;z["null"]=function(){return 0};Date.prototype.s=function(a,b){return b instanceof Date&&this.toString()===b.toString()};Ja.number=function(a,b){return a===b};Ea["function"]=!0;Fa["function"]=function(){return null};qa["function"]=!0;Ka._=function(a){return a[aa]||(a[aa]=++ba)};function gb(a){return a+1}
var hb=function(){function a(a,b,c,d){for(var l=z(a);;)if(d<l)c=b.a?b.a(c,A.a(a,d)):b.call(null,c,A.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=z(a),l=0;;)if(l<d)c=b.a?b.a(c,A.a(a,l)):b.call(null,c,A.a(a,l)),l+=1;else return c}function c(a,b){var c=z(a);if(0===c)return b.K?b.K():b.call(null);for(var d=A.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,A.a(a,l)):b.call(null,d,A.a(a,l)),l+=1;else return d}var d=null,d=function(d,g,h,k){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,
d,g,h);case 4:return a.call(this,d,g,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.i=a;return d}(),ib=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.K?b.K():b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,g,h,k){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,d,g,h);case 4:return a.call(this,d,g,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.i=a;return d}();function jb(a){return a?a.f&2||a.$a?!0:a.f?!1:s(ra,a):s(ra,a)}function kb(a){return a?a.f&16||a.Ta?!0:a.f?!1:s(ta,a):s(ta,a)}function fb(a,b){this.b=a;this.j=b;this.f=166199550;this.n=8192}f=fb.prototype;f.v=function(){return lb.d?lb.d(this):lb.call(null,this)};
f.Y=function(){return this.j+1<this.b.length?new fb(this.b,this.j+1):null};f.B=function(a,b){return U.a?U.a(b,this):U.call(null,b,this)};f.toString=function(){return I(this)};f.N=function(a,b){return ib.i(this.b,b,this.b[this.j],this.j+1)};f.O=function(a,b,c){return ib.i(this.b,b,c,this.j)};f.C=function(){return this};f.F=function(){return this.b.length-this.j};f.P=function(){return this.b[this.j]};f.Q=function(){return this.j+1<this.b.length?new fb(this.b,this.j+1):Q};
f.s=function(a,b){return mb.a?mb.a(this,b):mb.call(null,this,b)};f.w=function(a,b){var c=b+this.j;return c<this.b.length?this.b[c]:null};f.S=function(a,b,c){a=b+this.j;return a<this.b.length?this.b[a]:c};
var nb=function(){function a(a,b){return b<a.length?new fb(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}(),T=function(){function a(a,b){return nb.a(a,b)}function b(a){return nb.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.d=b;c.a=a;return c}();Ja._=function(a,b){return a===b};
var ob=function(){function a(a,b){return null!=a?sa(a,b):sa(Q,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=T(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(r(e))a=b.a(a,d),d=N(e),e=S(e);else return b.a(a,d)}a.o=2;a.l=function(a){var b=N(a);a=S(a);var d=N(a);a=P(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,g){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.g(b,e,T(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.o=2;b.l=c.l;b.a=a;b.g=c.g;return b}();function V(a){if(null!=a)if(a&&(a.f&2||a.$a))a=a.F(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(s(ra,a))a=z(a);else if(v)a:{a=M(a);for(var b=0;;){if(jb(a)){a=b+z(a);break a}a=S(a);b+=1}a=void 0}else a=null;else a=0;return a}
var pb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return M(a)?N(a):c;if(kb(a))return A.c(a,b,c);if(M(a))a=S(a),b-=1;else return v?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(M(a))return N(a);throw Error("Index out of bounds");}if(kb(a))return A.a(a,b);if(M(a)){var c=S(a),h=b-1;a=c;b=h}else{if(v)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),qb=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.f&16||a.Ta))return a.S(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(s(ta,a))return A.a(a,b);if(a?a.f&64||a.ra||(a.f?0:s(ua,a)):s(ua,a))return pb.c(a,b,c);if(v)throw Error([x("nth not supported on this type "),x(pa(oa(a)))].join(""));return null}
function b(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.f&16||a.Ta))return a.w(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(s(ta,a))return A.a(a,b);if(a?a.f&64||a.ra||(a.f?0:s(ua,a)):s(ua,a))return pb.a(a,b);if(v)throw Error([x("nth not supported on this type "),x(pa(oa(a)))].join(""));return null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),rb=function(){function a(a,b,c){return null!=a?a&&(a.f&256||a.bb)?a.M(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:s(va,a)?F.c(a,b,c):v?c:null:c}function b(a,b){return null==a?null:a&&(a.f&256||a.bb)?a.L(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:s(va,a)?F.a(a,b):null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),tb=function(){function a(a,b,c){return null!=a?wa(a,b,c):sb.a?sb.a([b],[c]):sb.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=T(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.c(a,d,e),r(l))d=N(l),e=N(S(l)),l=S(S(l));else return a}a.o=3;a.l=function(a){var b=N(a);a=S(a);var d=N(a);
a=S(a);var l=N(a);a=P(a);return c(b,d,l,a)};a.g=c;return a}(),b=function(b,e,g,h){switch(arguments.length){case 3:return a.call(this,b,e,g);default:return c.g(b,e,g,T(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.o=3;b.l=c.l;b.c=a;b.g=c.g;return b}();function ub(a){var b="function"==n(a);return b?b:a?r(r(null)?null:a.qb)?!0:a.Ab?!1:s(qa,a):s(qa,a)}function vb(a){var b=null!=a;return(b?a?a.f&131072||a.eb||(a.f?0:s(Ea,a)):s(Ea,a):b)?Fa(a):null}var wb={},xb=0;
function L(a){if(a&&(a.f&4194304||a.tb))a=a.v(null);else if("number"===typeof a)a=Math.floor(a)%2147483647;else if(!0===a)a=1;else if(!1===a)a=0;else if("string"===typeof a){255<xb&&(wb={},xb=0);var b=wb[a];if("number"!==typeof b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;wb[a]=b;xb+=1}a=b}else a=null==a?0:v?Ka(a):null;return a}function yb(a){return a?a.f&16384||a.yb?!0:a.f?!1:s(Ca,a):s(Ca,a)}function zb(a){return a?a.n&512||a.rb?!0:!1:!1}
function Ab(a){var b=[];ca(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Cb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}function Db(a){return r(a)?!0:!1}function bb(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(oa(a)===oa(b))return a&&(a.n&2048||a.va)?a.wa(null,b):a>b?1:a<b?-1:0;if(v)throw Error("compare on non-nil objects of different types");return null}
var Eb=function(){function a(a,b,c,h){for(;;){var k=bb(qb.a(a,h),qb.a(b,h));if(0===k&&h+1<c)h+=1;else return k}}function b(a,b){var g=V(a),h=V(b);return g<h?-1:g>h?1:v?c.i(a,b,g,0):null}var c=null,c=function(c,e,g,h){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,g,h)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.i=a;return c}(),W=function(){function a(a,b,c){for(c=M(c);;)if(c)b=a.a?a.a(b,N(c)):a.call(null,b,N(c)),c=S(c);else return b}function b(a,
b){var c=M(b);return c?Fb.c?Fb.c(a,N(c),S(c)):Fb.call(null,a,N(c),S(c)):a.K?a.K():a.call(null)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),Fb=function(){function a(a,b,c){return c&&(c.f&524288||c.gb)?c.O(null,a,b):c instanceof Array?ib.c(c,a,b):"string"===typeof c?ib.c(c,a,b):s(Ha,c)?Ia.c(c,a,b):v?W.c(a,b,c):null}function b(a,b){return b&&(b.f&524288||
b.gb)?b.N(null,a):b instanceof Array?ib.a(b,a):"string"===typeof b?ib.a(b,a):s(Ha,b)?Ia.a(b,a):v?W.a(a,b):null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Gb(a){return 0<=a?Math.floor.d?Math.floor.d(a):Math.floor.call(null,a):Math.ceil.d?Math.ceil.d(a):Math.ceil.call(null,a)}
function Hb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var x=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=T(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new ea(b.d(a)),l=d;;)if(r(l))e=e.append(b.d(N(l))),l=S(l);else return e.toString()}a.o=1;a.l=function(a){var b=N(a);a=P(a);return c(b,a)};a.g=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.g(b,T(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.o=1;b.l=c.l;b.K=function(){return""};b.d=a;b.g=c.g;return b}();function mb(a,b){return Db((b?b.f&16777216||b.xb||(b.f?0:s(Na,b)):s(Na,b))?function(){for(var c=M(a),d=M(b);;){if(null==c)return null==d;if(null==d)return!1;if(K.a(N(c),N(d)))c=S(c),d=S(d);else return v?!1:null}}():null)}function eb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function lb(a){if(M(a)){var b=L(N(a));for(a=S(a);;){if(null==a)return b;b=eb(b,L(N(a)));a=S(a)}}else return 0}function Ib(a){var b=0;for(a=M(a);;)if(a){var c=N(a),b=(b+(L(Jb.d?Jb.d(c):Jb.call(null,c))^L(Kb.d?Kb.d(c):Kb.call(null,c))))%4503599627370496;a=S(a)}else return b}function Lb(a,b,c,d,e){this.k=a;this.ta=b;this.ea=c;this.count=d;this.h=e;this.f=65937646;this.n=8192}f=Lb.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.Y=function(){return 1===this.count?null:this.ea};
f.B=function(a,b){return new Lb(this.k,b,this,this.count+1,null)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return this};f.F=function(){return this.count};f.P=function(){return this.ta};f.Q=function(){return 1===this.count?Q:this.ea};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Lb(b,this.ta,this.ea,this.count,this.h)};f.G=function(){return this.k};
function Mb(a){this.k=a;this.f=65937614;this.n=8192}f=Mb.prototype;f.v=function(){return 0};f.Y=function(){return null};f.B=function(a,b){return new Lb(this.k,b,null,1,null)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return null};f.F=function(){return 0};f.P=function(){return null};f.Q=function(){return Q};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Mb(b)};f.G=function(){return this.k};
var Q=new Mb(null),Nb=function(){function a(a){var d=null;0<arguments.length&&(d=T(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof fb&&0===a.j)b=a.b;else a:{for(b=[];;)if(null!=a)b.push(a.P(null)),a=a.Y(null);else break a;b=void 0}a=b.length;for(var e=Q;;)if(0<a){var g=a-1,e=e.B(null,b[a-1]);a=g}else return e}a.o=0;a.l=function(a){a=M(a);return b(a)};a.g=b;return a}();
function Ob(a,b,c,d){this.k=a;this.ta=b;this.ea=c;this.h=d;this.f=65929452;this.n=8192}f=Ob.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.Y=function(){return null==this.ea?null:M(this.ea)};f.B=function(a,b){return new Ob(null,b,this,this.h)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return this};f.P=function(){return this.ta};f.Q=function(){return null==this.ea?Q:this.ea};
f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Ob(b,this.ta,this.ea,this.h)};f.G=function(){return this.k};function U(a,b){var c=null==b;return(c?c:b&&(b.f&64||b.ra))?new Ob(null,a,b,null):new Ob(null,a,M(b),null)}function X(a,b,c,d){this.J=a;this.name=b;this.ga=c;this.ia=d;this.f=2153775105;this.n=4096}f=X.prototype;f.t=function(a,b){return H(b,[x(":"),x(this.ga)].join(""))};f.v=function(){null==this.ia&&(this.ia=eb(L(this.J),L(this.name))+2654435769);return this.ia};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return rb.a(c,this);case 3:return rb.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return rb.a(a,this)};f.a=function(a,b){return rb.c(a,this,b)};f.s=function(a,b){return b instanceof X?this.ga===b.ga:!1};f.toString=function(){return[x(":"),x(this.ga)].join("")};
var Qb=function(){function a(a,b){return new X(a,b,[x(r(a)?[x(a),x("/")].join(""):null),x(b)].join(""),null)}function b(a){if(a instanceof X)return a;if(a instanceof db){var b;if(a&&(a.n&4096||a.fb))b=a.J;else throw Error([x("Doesn't support namespace: "),x(a)].join(""));return new X(b,Pb.d?Pb.d(a):Pb.call(null,a),a.ha,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new X(b[0],b[1],a,null):new X(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,
c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}();function Rb(a,b,c,d){this.k=a;this.na=b;this.p=c;this.h=d;this.n=0;this.f=32374988}f=Rb.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.Y=function(){Ma(this);return null==this.p?null:S(this.p)};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};function Sb(a){null!=a.na&&(a.p=a.na.K?a.na.K():a.na.call(null),a.na=null);return a.p}
f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){Sb(this);if(null==this.p)return null;for(var a=this.p;;)if(a instanceof Rb)a=Sb(a);else return this.p=a,M(this.p)};f.P=function(){Ma(this);return null==this.p?null:N(this.p)};f.Q=function(){Ma(this);return null!=this.p?P(this.p):Q};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Rb(b,this.na,this.p,this.h)};f.G=function(){return this.k};
function Tb(a,b){this.Aa=a;this.end=b;this.n=0;this.f=2}Tb.prototype.F=function(){return this.end};Tb.prototype.add=function(a){this.Aa[this.end]=a;return this.end+=1};Tb.prototype.ba=function(){var a=new Ub(this.Aa,0,this.end);this.Aa=null;return a};function Ub(a,b,c){this.b=a;this.q=b;this.end=c;this.n=0;this.f=524306}f=Ub.prototype;f.N=function(a,b){return ib.i(this.b,b,this.b[this.q],this.q+1)};f.O=function(a,b,c){return ib.i(this.b,b,c,this.q)};
f.Sa=function(){if(this.q===this.end)throw Error("-drop-first of empty chunk");return new Ub(this.b,this.q+1,this.end)};f.w=function(a,b){return this.b[this.q+b]};f.S=function(a,b,c){return 0<=b&&b<this.end-this.q?this.b[this.q+b]:c};f.F=function(){return this.end-this.q};
var Vb=function(){function a(a,b,c){return new Ub(a,b,c)}function b(a,b){return new Ub(a,b,a.length)}function c(a){return new Ub(a,0,a.length)}var d=null,d=function(d,g,h){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,g);case 3:return a.call(this,d,g,h)}throw Error("Invalid arity: "+arguments.length);};d.d=c;d.a=b;d.c=a;return d}();function Wb(a,b,c,d){this.ba=a;this.Z=b;this.k=c;this.h=d;this.f=31850732;this.n=1536}f=Wb.prototype;
f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.Y=function(){if(1<z(this.ba))return new Wb(Wa(this.ba),this.Z,this.k,null);var a=Ma(this.Z);return null==a?null:a};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};f.C=function(){return this};f.P=function(){return A.a(this.ba,0)};f.Q=function(){return 1<z(this.ba)?new Wb(Wa(this.ba),this.Z,this.k,null):null==this.Z?Q:this.Z};f.Ba=function(){return null==this.Z?null:this.Z};f.s=function(a,b){return mb(this,b)};
f.I=function(a,b){return new Wb(this.ba,this.Z,b,this.h)};f.G=function(){return this.k};f.Ca=function(){return this.ba};f.Da=function(){return null==this.Z?Q:this.Z};function Xb(a){for(var b=[];;)if(M(a))b.push(N(a)),a=S(a);else return b}function Yb(a,b){if(jb(a))return V(a);for(var c=a,d=b,e=0;;)if(0<d&&M(c))c=S(c),d-=1,e+=1;else return e}
var $b=function Zb(b){return null==b?null:null==S(b)?M(N(b)):v?U(N(b),Zb(S(b))):null},ac=function(){function a(a,b,c,d){return U(a,U(b,U(c,d)))}function b(a,b,c){return U(a,U(b,c))}var c=null,d=function(){function a(c,d,e,m,p){var t=null;4<arguments.length&&(t=T(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,t)}function b(a,c,d,e,g){return U(a,U(c,U(d,U(e,$b(g)))))}a.o=4;a.l=function(a){var c=N(a);a=S(a);var d=N(a);a=S(a);var e=N(a);a=S(a);var p=N(a);a=P(a);return b(c,d,e,
p,a)};a.g=b;return a}(),c=function(c,g,h,k,l){switch(arguments.length){case 1:return M(c);case 2:return U(c,g);case 3:return b.call(this,c,g,h);case 4:return a.call(this,c,g,h,k);default:return d.g(c,g,h,k,T(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.o=4;c.l=d.l;c.d=function(a){return M(a)};c.a=function(a,b){return U(a,b)};c.c=b;c.i=a;c.g=d.g;return c}(),bc=function(){var a=null,b=function(){function a(c,g,h,k){var l=null;3<arguments.length&&(l=T(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,g,h,l)}function b(a,c,d,k){for(;;)if(a=Ua(a,c,d),r(k))c=N(k),d=N(S(k)),k=S(S(k));else return a}a.o=3;a.l=function(a){var c=N(a);a=S(a);var h=N(a);a=S(a);var k=N(a);a=P(a);return b(c,h,k,a)};a.g=b;return a}(),a=function(a,d,e,g){switch(arguments.length){case 3:return Ua(a,d,e);default:return b.g(a,d,e,T(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.o=3;a.l=b.l;a.c=function(a,b,e){return Ua(a,b,e)};a.g=b.g;return a}();
function cc(a,b,c){var d=M(c);if(0===b)return a.K?a.K():a.call(null);c=C(d);var e=E(d);if(1===b)return a.d?a.d(c):a.d?a.d(c):a.call(null,c);var d=C(e),g=E(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=C(g),h=E(g);if(3===b)return a.c?a.c(c,d,e):a.c?a.c(c,d,e):a.call(null,c,d,e);var g=C(h),k=E(h);if(4===b)return a.i?a.i(c,d,e,g):a.i?a.i(c,d,e,g):a.call(null,c,d,e,g);var h=C(k),l=E(k);if(5===b)return a.A?a.A(c,d,e,g,h):a.A?a.A(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=C(l),m=E(l);
if(6===b)return a.ca?a.ca(c,d,e,g,h,k):a.ca?a.ca(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=C(m),p=E(m);if(7===b)return a.ka?a.ka(c,d,e,g,h,k,l):a.ka?a.ka(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=C(p),t=E(p);if(8===b)return a.Pa?a.Pa(c,d,e,g,h,k,l,m):a.Pa?a.Pa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var p=C(t),u=E(t);if(9===b)return a.Qa?a.Qa(c,d,e,g,h,k,l,m,p):a.Qa?a.Qa(c,d,e,g,h,k,l,m,p):a.call(null,c,d,e,g,h,k,l,m,p);var t=C(u),D=E(u);if(10===b)return a.Ea?a.Ea(c,d,e,g,h,k,l,m,p,
t):a.Ea?a.Ea(c,d,e,g,h,k,l,m,p,t):a.call(null,c,d,e,g,h,k,l,m,p,t);var u=C(D),B=E(D);if(11===b)return a.Fa?a.Fa(c,d,e,g,h,k,l,m,p,t,u):a.Fa?a.Fa(c,d,e,g,h,k,l,m,p,t,u):a.call(null,c,d,e,g,h,k,l,m,p,t,u);var D=C(B),J=E(B);if(12===b)return a.Ga?a.Ga(c,d,e,g,h,k,l,m,p,t,u,D):a.Ga?a.Ga(c,d,e,g,h,k,l,m,p,t,u,D):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D);var B=C(J),O=E(J);if(13===b)return a.Ha?a.Ha(c,d,e,g,h,k,l,m,p,t,u,D,B):a.Ha?a.Ha(c,d,e,g,h,k,l,m,p,t,u,D,B):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B);var J=C(O),
R=E(O);if(14===b)return a.Ia?a.Ia(c,d,e,g,h,k,l,m,p,t,u,D,B,J):a.Ia?a.Ia(c,d,e,g,h,k,l,m,p,t,u,D,B,J):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J);var O=C(R),da=E(R);if(15===b)return a.Ja?a.Ja(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O):a.Ja?a.Ja(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J,O);var R=C(da),ka=E(da);if(16===b)return a.Ka?a.Ka(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R):a.Ka?a.Ka(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R);var da=C(ka),Aa=E(ka);if(17===
b)return a.La?a.La(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da):a.La?a.La(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da);var ka=C(Aa),Bb=E(Aa);if(18===b)return a.Ma?a.Ma(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka):a.Ma?a.Ma(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka);Aa=C(Bb);Bb=E(Bb);if(19===b)return a.Na?a.Na(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka,Aa):a.Na?a.Na(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka,Aa):a.call(null,c,d,e,g,h,k,l,
m,p,t,u,D,B,J,O,R,da,ka,Aa);var nc=C(Bb);E(Bb);if(20===b)return a.Oa?a.Oa(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka,Aa,nc):a.Oa?a.Oa(c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka,Aa,nc):a.call(null,c,d,e,g,h,k,l,m,p,t,u,D,B,J,O,R,da,ka,Aa,nc);throw Error("Only up to 20 arguments supported on functions");}
var dc=function(){function a(a,b,c,d,e){b=ac.i(b,c,d,e);c=a.o;return a.l?(d=Yb(b,c+1),d<=c?cc(a,d,b):a.l(b)):a.apply(a,Xb(b))}function b(a,b,c,d){b=ac.c(b,c,d);c=a.o;return a.l?(d=Yb(b,c+1),d<=c?cc(a,d,b):a.l(b)):a.apply(a,Xb(b))}function c(a,b,c){b=ac.a(b,c);c=a.o;if(a.l){var d=Yb(b,c+1);return d<=c?cc(a,d,b):a.l(b)}return a.apply(a,Xb(b))}function d(a,b){var c=a.o;if(a.l){var d=Yb(b,c+1);return d<=c?cc(a,d,b):a.l(b)}return a.apply(a,Xb(b))}var e=null,g=function(){function a(c,d,e,g,h,D){var B=null;
5<arguments.length&&(B=T(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,g,h,B)}function b(a,c,d,e,g,h){c=U(c,U(d,U(e,U(g,$b(h)))));d=a.o;return a.l?(e=Yb(c,d+1),e<=d?cc(a,e,c):a.l(c)):a.apply(a,Xb(c))}a.o=5;a.l=function(a){var c=N(a);a=S(a);var d=N(a);a=S(a);var e=N(a);a=S(a);var g=N(a);a=S(a);var h=N(a);a=P(a);return b(c,d,e,g,h,a)};a.g=b;return a}(),e=function(e,k,l,m,p,t){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,p);default:return g.g(e,k,l,m,p,T(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.o=5;e.l=g.l;e.a=d;e.c=c;e.i=b;e.A=a;e.g=g.g;return e}();function ec(a,b){for(;;){if(null==M(b))return!0;if(r(a.d?a.d(N(b)):a.call(null,N(b)))){var c=a,d=S(b);a=c;b=d}else return v?!1:null}}function fc(a){return a}
var gc=function(){function a(a,b,c,e){return new Rb(null,function(){var m=M(b),p=M(c),t=M(e);return m&&p&&t?U(a.c?a.c(N(m),N(p),N(t)):a.call(null,N(m),N(p),N(t)),d.i(a,P(m),P(p),P(t))):null},null,null)}function b(a,b,c){return new Rb(null,function(){var e=M(b),m=M(c);return e&&m?U(a.a?a.a(N(e),N(m)):a.call(null,N(e),N(m)),d.c(a,P(e),P(m))):null},null,null)}function c(a,b){return new Rb(null,function(){var c=M(b);if(c){if(zb(c)){for(var e=Xa(c),m=V(e),p=new Tb(Array(m),0),t=0;;)if(t<m){var u=a.d?a.d(A.a(e,
t)):a.call(null,A.a(e,t));p.add(u);t+=1}else break;e=p.ba();c=d.a(a,Ya(c));return 0===z(e)?c:new Wb(e,c,null,null)}return U(a.d?a.d(N(c)):a.call(null,N(c)),d.a(a,P(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,g,t){var u=null;4<arguments.length&&(u=T(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,g,u)}function b(a,c,e,g,h){var u=function B(a){return new Rb(null,function(){var b=d.a(M,a);return ec(fc,b)?U(d.a(N,b),B(d.a(P,b))):null},null,null)};return d.a(function(){return function(b){return dc.a(a,
b)}}(u),u(ob.g(h,g,T([e,c],0))))}a.o=4;a.l=function(a){var c=N(a);a=S(a);var d=N(a);a=S(a);var e=N(a);a=S(a);var g=N(a);a=P(a);return b(c,d,e,g,a)};a.g=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,T(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.o=4;d.l=e.l;d.a=c;d.c=b;d.i=a;d.g=e.g;return d}();function hc(a,b){this.m=a;this.b=b}
function ic(a){return new hc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function jc(a){a=a.e;return 32>a?0:a-1>>>5<<5}function kc(a,b,c){for(;;){if(0===b)return c;var d=ic(a);d.b[0]=c;c=d;b-=5}}var mc=function lc(b,c,d,e){var g=new hc(d.m,y(d.b)),h=b.e-1>>>c&31;5===c?g.b[h]=e:(d=d.b[h],b=null!=d?lc(b,c-5,d,e):kc(null,c-5,e),g.b[h]=b);return g};
function oc(a,b){throw Error([x("No item "),x(a),x(" in vector of length "),x(b)].join(""));}function pc(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.b[0];else return b.b}function qc(a,b){if(b>=jc(a))return a.D;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function rc(a,b){return 0<=b&&b<a.e?qc(a,b):oc(b,a.e)}var tc=function sc(b,c,d,e,g){var h=new hc(d.m,y(d.b));if(0===c)h.b[e&31]=g;else{var k=e>>>c&31;b=sc(b,c-5,d.b[k],e,g);h.b[k]=b}return h};
function Y(a,b,c,d,e,g){this.k=a;this.e=b;this.shift=c;this.root=d;this.D=e;this.h=g;this.n=8196;this.f=167668511}f=Y.prototype;f.xa=function(){return new uc(this.e,this.shift,vc.d?vc.d(this.root):vc.call(null,this.root),wc.d?wc.d(this.D):wc.call(null,this.D))};f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};
f.qa=function(a,b,c){if("number"===typeof b)return Da(this,b,c);throw Error("Vector's key for assoc must be a number.");};f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.w(null,c);case 3:return this.S(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return this.w(null,a)};f.a=function(a,b){return this.S(null,a,b)};
f.B=function(a,b){if(32>this.e-jc(this)){for(var c=this.D.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.D[e],e+=1;else break;d[c]=b;return new Y(this.k,this.e+1,this.shift,this.root,d,null)}c=(d=this.e>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=ic(null),d.b[0]=this.root,e=kc(null,this.shift,new hc(null,this.D)),d.b[1]=e):d=mc(this,this.shift,this.root,new hc(null,this.D));return new Y(this.k,this.e+1,c,d,[b],null)};f.Ua=function(){return A.a(this,0)};f.Va=function(){return A.a(this,1)};
f.toString=function(){return I(this)};f.N=function(a,b){return hb.a(this,b)};f.O=function(a,b,c){return hb.c(this,b,c)};f.C=function(){return 0===this.e?null:32>=this.e?new fb(this.D,0):v?Z.i?Z.i(this,pc(this),0,0):Z.call(null,this,pc(this),0,0):null};f.F=function(){return this.e};
f.Ra=function(a,b,c){if(0<=b&&b<this.e)return jc(this)<=b?(a=y(this.D),a[b&31]=c,new Y(this.k,this.e,this.shift,this.root,a,null)):new Y(this.k,this.e,this.shift,tc(this,this.shift,this.root,b,c),this.D,null);if(b===this.e)return sa(this,c);if(v)throw Error([x("Index "),x(b),x(" out of bounds  [0,"),x(this.e),x("]")].join(""));return null};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Y(b,this.e,this.shift,this.root,this.D,this.h)};f.G=function(){return this.k};
f.w=function(a,b){return rc(this,b)[b&31]};f.S=function(a,b,c){return 0<=b&&b<this.e?qc(this,b)[b&31]:c};var xc=new hc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),yc=new Y(null,0,5,xc,[],0);function zc(a,b,c,d,e,g){this.r=a;this.U=b;this.j=c;this.q=d;this.k=e;this.h=g;this.f=32243948;this.n=1536}f=zc.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};
f.Y=function(){if(this.q+1<this.U.length){var a=Z.i?Z.i(this.r,this.U,this.j,this.q+1):Z.call(null,this.r,this.U,this.j,this.q+1);return null==a?null:a}return Za(this)};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};f.N=function(a,b){return hb.a(Ac.c?Ac.c(this.r,this.j+this.q,V(this.r)):Ac.call(null,this.r,this.j+this.q,V(this.r)),b)};f.O=function(a,b,c){return hb.c(Ac.c?Ac.c(this.r,this.j+this.q,V(this.r)):Ac.call(null,this.r,this.j+this.q,V(this.r)),b,c)};f.C=function(){return this};
f.P=function(){return this.U[this.q]};f.Q=function(){if(this.q+1<this.U.length){var a=Z.i?Z.i(this.r,this.U,this.j,this.q+1):Z.call(null,this.r,this.U,this.j,this.q+1);return null==a?Q:a}return Ya(this)};f.Ba=function(){var a=this.j+this.U.length;return a<z(this.r)?Z.i?Z.i(this.r,qc(this.r,a),a,0):Z.call(null,this.r,qc(this.r,a),a,0):null};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return Z.A?Z.A(this.r,this.U,this.j,this.q,b):Z.call(null,this.r,this.U,this.j,this.q,b)};
f.Ca=function(){return Vb.a(this.U,this.q)};f.Da=function(){var a=this.j+this.U.length;return a<z(this.r)?Z.i?Z.i(this.r,qc(this.r,a),a,0):Z.call(null,this.r,qc(this.r,a),a,0):Q};
var Z=function(){function a(a,b,c,d,l){return new zc(a,b,c,d,l,null)}function b(a,b,c,d){return new zc(a,b,c,d,null,null)}function c(a,b,c){return new zc(a,rc(a,b),b,c,null,null)}var d=null,d=function(d,g,h,k,l){switch(arguments.length){case 3:return c.call(this,d,g,h);case 4:return b.call(this,d,g,h,k);case 5:return a.call(this,d,g,h,k,l)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.i=b;d.A=a;return d}();
function Bc(a,b,c,d,e){this.k=a;this.$=b;this.start=c;this.end=d;this.h=e;this.f=166617887;this.n=8192}f=Bc.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};f.qa=function(a,b,c){if("number"===typeof b)return Da(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.w(null,c);case 3:return this.S(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return this.w(null,a)};f.a=function(a,b){return this.S(null,a,b)};
f.B=function(a,b){return Cc.A?Cc.A(this.k,Da(this.$,this.end,b),this.start,this.end+1,null):Cc.call(null,this.k,Da(this.$,this.end,b),this.start,this.end+1,null)};f.toString=function(){return I(this)};f.N=function(a,b){return hb.a(this,b)};f.O=function(a,b,c){return hb.c(this,b,c)};f.C=function(){var a=this;return function(b){return function d(e){return e===a.end?null:U(A.a(a.$,e),new Rb(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
f.F=function(){return this.end-this.start};f.Ra=function(a,b,c){var d=this,e=d.start+b;return Cc.A?Cc.A(d.k,tb.c(d.$,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):Cc.call(null,d.k,tb.c(d.$,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return Cc.A?Cc.A(b,this.$,this.start,this.end,this.h):Cc.call(null,b,this.$,this.start,this.end,this.h)};f.G=function(){return this.k};
f.w=function(a,b){return 0>b||this.end<=this.start+b?oc(b,this.end-this.start):A.a(this.$,this.start+b)};f.S=function(a,b,c){return 0>b||this.end<=this.start+b?c:A.c(this.$,this.start+b,c)};function Cc(a,b,c,d,e){for(;;)if(b instanceof Bc)c=b.start+c,d=b.start+d,b=b.$;else{var g=V(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new Bc(a,b,c,d,e)}}
var Ac=function(){function a(a,b,c){return Cc(null,a,b,c,null)}function b(a,b){return c.c(a,b,V(a))}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function vc(a){return new hc({},y(a.b))}
function wc(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Cb(a,0,b,0,a.length);return b}var Ec=function Dc(b,c,d,e){d=b.root.m===d.m?d:new hc(b.root.m,y(d.b));var g=b.e-1>>>c&31;if(5===c)b=e;else{var h=d.b[g];b=null!=h?Dc(b,c-5,h,e):kc(b.root.m,c-5,e)}d.b[g]=b;return d};function uc(a,b,c,d){this.e=a;this.shift=b;this.root=c;this.D=d;this.f=275;this.n=88}f=uc.prototype;
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};
f.w=function(a,b){if(this.root.m)return rc(this,b)[b&31];throw Error("nth after persistent!");};f.S=function(a,b,c){return 0<=b&&b<this.e?A.a(this,b):c};f.F=function(){if(this.root.m)return this.e;throw Error("count after persistent!");};
f.Wa=function(a,b,c){var d=this;if(d.root.m){if(0<=b&&b<d.e)return jc(this)<=b?d.D[b&31]=c:(a=function(){return function g(a,k){var l=d.root.m===k.m?k:new hc(d.root.m,y(k.b));if(0===a)l.b[b&31]=c;else{var m=b>>>a&31,p=g(a-5,l.b[m]);l.b[m]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.e)return Sa(this,c);if(v)throw Error([x("Index "),x(b),x(" out of bounds for TransientVector of length"),x(d.e)].join(""));return null}throw Error("assoc! after persistent!");};
f.sa=function(a,b,c){if("number"===typeof b)return Va(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.ya=function(a,b){if(this.root.m){if(32>this.e-jc(this))this.D[this.e&31]=b;else{var c=new hc(this.root.m,this.D),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.D=d;if(this.e>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=kc(this.root.m,this.shift,c);this.root=new hc(this.root.m,d);this.shift=e}else this.root=Ec(this,this.shift,this.root,c)}this.e+=1;return this}throw Error("conj! after persistent!");};f.za=function(){if(this.root.m){this.root.m=null;var a=this.e-jc(this),b=Array(a);Cb(this.D,0,b,0,a);return new Y(null,this.e,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function Fc(){this.n=0;this.f=2097152}Fc.prototype.s=function(){return!1};var Gc=new Fc;
function Hc(a,b){return Db((null==b?0:b?b.f&1024||b.ub||(b.f?0:s(xa,b)):s(xa,b))?V(a)===V(b)?ec(fc,gc.a(function(a){return K.a(rb.c(b,N(a),Gc),N(S(a)))},a)):null:null)}
function Ic(a,b){var c=a.b;if(b instanceof X)a:{for(var d=c.length,e=b.ga,g=0;;){if(d<=g){c=-1;break a}var h=c[g];if(h instanceof X&&e===h.ga){c=g;break a}if(v)g+=2;else{c=null;break a}}c=void 0}else if("string"==typeof b||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(v)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof db)a:{d=c.length;e=b.ha;for(g=0;;){if(d<=g){c=-1;break a}h=c[g];if(h instanceof db&&e===h.ha){c=g;break a}if(v)g+=2;else{c=null;
break a}}c=void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(v)e+=2;else{c=null;break a}}c=void 0}else if(v)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(K.a(b,c[e])){c=e;break a}if(v)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function Jc(a,b,c){this.b=a;this.j=b;this.oa=c;this.n=0;this.f=32374990}f=Jc.prototype;f.v=function(){return lb(this)};f.Y=function(){return this.j<this.b.length-2?new Jc(this.b,this.j+2,this.oa):null};
f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return this};f.F=function(){return(this.b.length-this.j)/2};f.P=function(){return new Y(null,2,5,xc,[this.b[this.j],this.b[this.j+1]],null)};f.Q=function(){return this.j<this.b.length-2?new Jc(this.b,this.j+2,this.oa):Q};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new Jc(this.b,this.j,b)};f.G=function(){return this.oa};
function q(a,b,c,d){this.k=a;this.e=b;this.b=c;this.h=d;this.n=8196;this.f=16123663}f=q.prototype;f.xa=function(){return new Kc({},this.b.length,y(this.b))};f.v=function(){var a=this.h;return null!=a?a:this.h=a=Ib(this)};f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){a=Ic(this,b);return-1===a?c:this.b[a+1]};
f.qa=function(a,b,c){a=Ic(this,b);if(-1===a){if(this.e<Lc){a=this.b;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new q(this.k,this.e+1,e,null)}a=Ga;d=wa;e=Mc;null!=e?e&&(e.n&4||e.sb)?(e=Fb.c(Sa,Ra(e),this),e=Ta(e)):e=Fb.c(sa,e,this):e=Fb.c(ob,Q,this);return a(d(e,b,c),this.k)}return c===this.b[a+1]?this:v?(b=y(this.b),b[a+1]=c,new q(this.k,this.e,b,null)):null};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.B=function(a,b){return yb(b)?wa(this,A.a(b,0),A.a(b,1)):Fb.c(sa,this,b)};f.toString=function(){return I(this)};
f.C=function(){return 0<=this.b.length-2?new Jc(this.b,0,null):null};f.F=function(){return this.e};f.s=function(a,b){return Hc(this,b)};f.I=function(a,b){return new q(b,this.e,this.b,this.h)};f.G=function(){return this.k};var Lc=8;function Kc(a,b,c){this.la=a;this.da=b;this.b=c;this.n=56;this.f=258}f=Kc.prototype;
f.sa=function(a,b,c){if(r(this.la)){a=Ic(this,b);if(-1===a)return this.da+2<=2*Lc?(this.da+=2,this.b.push(b),this.b.push(c),this):bc.c(Nc.a?Nc.a(this.da,this.b):Nc.call(null,this.da,this.b),b,c);c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};
f.ya=function(a,b){if(r(this.la)){if(b?b.f&2048||b.cb||(b.f?0:s(ya,b)):s(ya,b))return Ua(this,Jb.d?Jb.d(b):Jb.call(null,b),Kb.d?Kb.d(b):Kb.call(null,b));for(var c=M(b),d=this;;){var e=N(c);if(r(e))c=S(c),d=Ua(d,Jb.d?Jb.d(e):Jb.call(null,e),Kb.d?Kb.d(e):Kb.call(null,e));else return d}}else throw Error("conj! after persistent!");};f.za=function(){if(r(this.la))return this.la=!1,new q(null,Gb((this.da-this.da%2)/2),this.b,null);throw Error("persistent! called twice");};
f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){if(r(this.la))return a=Ic(this,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};f.F=function(){if(r(this.la))return Gb((this.da-this.da%2)/2);throw Error("count after persistent!");};function Nc(a,b){for(var c=Ra(Mc),d=0;;)if(d<a)c=bc.c(c,b[d],b[d+1]),d+=2;else return c}function Oc(){this.aa=!1}function Pc(a,b){return a===b?!0:a===b||a instanceof X&&b instanceof X&&a.ga===b.ga?!0:v?K.a(a,b):null}
var Qc=function(){function a(a,b,c,h,k){a=y(a);a[b]=c;a[h]=k;return a}function b(a,b,c){a=y(a);a[b]=c;return a}var c=null,c=function(c,e,g,h,k){switch(arguments.length){case 3:return b.call(this,c,e,g);case 5:return a.call(this,c,e,g,h,k)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.A=a;return c}(),Rc=function(){function a(a,b,c,h,k,l){a=a.ma(b);a.b[c]=h;a.b[k]=l;return a}function b(a,b,c,h){a=a.ma(b);a.b[c]=h;return a}var c=null,c=function(c,e,g,h,k,l){switch(arguments.length){case 4:return b.call(this,
c,e,g,h);case 6:return a.call(this,c,e,g,h,k,l)}throw Error("Invalid arity: "+arguments.length);};c.i=b;c.ca=a;return c}();function Sc(a,b,c){this.m=a;this.u=b;this.b=c}f=Sc.prototype;
f.W=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Hb(this.u&h-1);if(0===(this.u&h)){var l=Hb(this.u);if(2*l<this.b.length){a=this.ma(a);b=a.b;g.aa=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];l-=1;c-=1;g-=1}b[2*k]=d;b[2*k+1]=e;a.u|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Tc.W(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.u>>>d&1)&&(k[d]=null!=this.b[e]?Tc.W(a,b+5,L(this.b[e]),this.b[e],this.b[e+1],g):this.b[e+1],e+=2),d+=1;else break;return new Uc(a,l+1,k)}return v?(b=Array(2*(l+4)),Cb(this.b,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Cb(this.b,2*k,b,2*(k+1),2*(l-k)),g.aa=!0,a=this.ma(a),a.b=b,a.u|=h,a):null}l=this.b[2*k];h=this.b[2*k+1];return null==l?(l=h.W(a,b+5,c,d,e,g),l===h?this:Rc.i(this,a,2*k+1,l)):Pc(d,l)?e===h?this:Rc.i(this,a,2*k+1,e):v?(g.aa=!0,Rc.ca(this,a,2*k,null,2*k+1,Vc.ka?Vc.ka(a,b+5,l,h,c,d,e):Vc.call(null,
a,b+5,l,h,c,d,e))):null};f.ua=function(){return Wc.d?Wc.d(this.b):Wc.call(null,this.b)};f.ma=function(a){if(a===this.m)return this;var b=Hb(this.u),c=Array(0>b?4:2*(b+1));Cb(this.b,0,c,0,2*b);return new Sc(a,this.u,c)};
f.V=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Hb(this.u&g-1);if(0===(this.u&g)){var k=Hb(this.u);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Tc.V(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.u>>>c&1)&&(h[c]=null!=this.b[d]?Tc.V(a+5,L(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new Uc(null,k+1,h)}a=Array(2*(k+1));Cb(this.b,0,a,
0,2*h);a[2*h]=c;a[2*h+1]=d;Cb(this.b,2*h,a,2*(h+1),2*(k-h));e.aa=!0;return new Sc(null,this.u|g,a)}k=this.b[2*h];g=this.b[2*h+1];return null==k?(k=g.V(a+5,b,c,d,e),k===g?this:new Sc(null,this.u,Qc.c(this.b,2*h+1,k))):Pc(c,k)?d===g?this:new Sc(null,this.u,Qc.c(this.b,2*h+1,d)):v?(e.aa=!0,new Sc(null,this.u,Qc.A(this.b,2*h,null,2*h+1,Vc.ca?Vc.ca(a+5,k,g,b,c,d):Vc.call(null,a+5,k,g,b,c,d)))):null};
f.ja=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.u&e))return d;var g=Hb(this.u&e-1),e=this.b[2*g],g=this.b[2*g+1];return null==e?g.ja(a+5,b,c,d):Pc(c,e)?g:v?d:null};var Tc=new Sc(null,0,[]);function Uc(a,b,c){this.m=a;this.e=b;this.b=c}f=Uc.prototype;f.W=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.b[h];if(null==k)return a=Rc.i(this,a,h,Tc.W(a,b+5,c,d,e,g)),a.e+=1,a;b=k.W(a,b+5,c,d,e,g);return b===k?this:Rc.i(this,a,h,b)};f.ua=function(){return Xc.d?Xc.d(this.b):Xc.call(null,this.b)};
f.ma=function(a){return a===this.m?this:new Uc(a,this.e,y(this.b))};f.V=function(a,b,c,d,e){var g=b>>>a&31,h=this.b[g];if(null==h)return new Uc(null,this.e+1,Qc.c(this.b,g,Tc.V(a+5,b,c,d,e)));a=h.V(a+5,b,c,d,e);return a===h?this:new Uc(null,this.e,Qc.c(this.b,g,a))};f.ja=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.ja(a+5,b,c,d):d};function Yc(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Pc(c,a[d]))return d;d+=2}else return-1}function Zc(a,b,c,d){this.m=a;this.fa=b;this.e=c;this.b=d}f=Zc.prototype;
f.W=function(a,b,c,d,e,g){if(c===this.fa){b=Yc(this.b,this.e,d);if(-1===b){if(this.b.length>2*this.e)return a=Rc.ca(this,a,2*this.e,d,2*this.e+1,e),g.aa=!0,a.e+=1,a;c=this.b.length;b=Array(c+2);Cb(this.b,0,b,0,c);b[c]=d;b[c+1]=e;g.aa=!0;g=this.e+1;a===this.m?(this.b=b,this.e=g,a=this):a=new Zc(this.m,this.fa,g,b);return a}return this.b[b+1]===e?this:Rc.i(this,a,b+1,e)}return(new Sc(a,1<<(this.fa>>>b&31),[null,this,null,null])).W(a,b,c,d,e,g)};
f.ua=function(){return Wc.d?Wc.d(this.b):Wc.call(null,this.b)};f.ma=function(a){if(a===this.m)return this;var b=Array(2*(this.e+1));Cb(this.b,0,b,0,2*this.e);return new Zc(a,this.fa,this.e,b)};f.V=function(a,b,c,d,e){return b===this.fa?(a=Yc(this.b,this.e,c),-1===a?(a=2*this.e,b=Array(a+2),Cb(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.aa=!0,new Zc(null,this.fa,this.e+1,b)):K.a(this.b[a],d)?this:new Zc(null,this.fa,this.e,Qc.c(this.b,a+1,d))):(new Sc(null,1<<(this.fa>>>a&31),[null,this])).V(a,b,c,d,e)};
f.ja=function(a,b,c,d){a=Yc(this.b,this.e,c);return 0>a?d:Pc(c,this.b[a])?this.b[a+1]:v?d:null};
var Vc=function(){function a(a,b,c,h,k,l,m){var p=L(c);if(p===k)return new Zc(null,p,2,[c,h,l,m]);var t=new Oc;return Tc.W(a,b,p,c,h,t).W(a,b,k,l,m,t)}function b(a,b,c,h,k,l){var m=L(b);if(m===h)return new Zc(null,m,2,[b,c,k,l]);var p=new Oc;return Tc.V(a,m,b,c,p).V(a,h,k,l,p)}var c=null,c=function(c,e,g,h,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,g,h,k,l);case 7:return a.call(this,c,e,g,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.ca=b;c.ka=a;return c}();
function $c(a,b,c,d,e){this.k=a;this.X=b;this.j=c;this.p=d;this.h=e;this.n=0;this.f=32374860}f=$c.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return this};f.P=function(){return null==this.p?new Y(null,2,5,xc,[this.X[this.j],this.X[this.j+1]],null):N(this.p)};
f.Q=function(){return null==this.p?Wc.c?Wc.c(this.X,this.j+2,null):Wc.call(null,this.X,this.j+2,null):Wc.c?Wc.c(this.X,this.j,S(this.p)):Wc.call(null,this.X,this.j,S(this.p))};f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new $c(b,this.X,this.j,this.p,this.h)};f.G=function(){return this.k};
var Wc=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new $c(null,a,b,null,null);var h=a[b+1];if(r(h)&&(h=h.ua(),r(h)))return new $c(null,a,b+2,h,null);b+=2}else return null;else return new $c(null,a,b,c,null)}function b(a){return c.c(a,0,null)}var c=null,c=function(c,e,g){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.c=a;return c}();
function ad(a,b,c,d,e){this.k=a;this.X=b;this.j=c;this.p=d;this.h=e;this.n=0;this.f=32374860}f=ad.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};f.N=function(a,b){return W.a(b,this)};f.O=function(a,b,c){return W.c(b,c,this)};f.C=function(){return this};f.P=function(){return N(this.p)};f.Q=function(){return Xc.i?Xc.i(null,this.X,this.j,S(this.p)):Xc.call(null,null,this.X,this.j,S(this.p))};
f.s=function(a,b){return mb(this,b)};f.I=function(a,b){return new ad(b,this.X,this.j,this.p,this.h)};f.G=function(){return this.k};
var Xc=function(){function a(a,b,c,h){if(null==h)for(h=b.length;;)if(c<h){var k=b[c];if(r(k)&&(k=k.ua(),r(k)))return new ad(a,b,c+1,k,null);c+=1}else return null;else return new ad(a,b,c,h,null)}function b(a){return c.i(null,a,0,null)}var c=null,c=function(c,e,g,h){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,g,h)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.i=a;return c}();
function bd(a,b,c,d,e,g){this.k=a;this.e=b;this.root=c;this.R=d;this.T=e;this.h=g;this.n=8196;this.f=16123663}f=bd.prototype;f.xa=function(){return new cd({},this.root,this.e,this.R,this.T)};f.v=function(){var a=this.h;return null!=a?a:this.h=a=Ib(this)};f.L=function(a,b){return F.c(this,b,null)};f.M=function(a,b,c){return null==b?this.R?this.T:c:null==this.root?c:v?this.root.ja(0,L(b),b,c):null};
f.qa=function(a,b,c){if(null==b)return this.R&&c===this.T?this:new bd(this.k,this.R?this.e:this.e+1,this.root,!0,c,null);a=new Oc;b=(null==this.root?Tc:this.root).V(0,L(b),b,c,a);return b===this.root?this:new bd(this.k,a.aa?this.e+1:this.e,b,this.R,this.T,null)};f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
f.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.B=function(a,b){return yb(b)?wa(this,A.a(b,0),A.a(b,1)):Fb.c(sa,this,b)};f.toString=function(){return I(this)};f.C=function(){if(0<this.e){var a=null!=this.root?this.root.ua():null;return this.R?U(new Y(null,2,5,xc,[null,this.T],null),a):a}return null};f.F=function(){return this.e};f.s=function(a,b){return Hc(this,b)};
f.I=function(a,b){return new bd(b,this.e,this.root,this.R,this.T,this.h)};f.G=function(){return this.k};var Mc=new bd(null,0,null,!1,null,0);function sb(a,b){for(var c=a.length,d=0,e=Ra(Mc);;)if(d<c)var g=d+1,e=e.sa(null,a[d],b[d]),d=g;else return Ta(e)}function cd(a,b,c,d,e){this.m=a;this.root=b;this.count=c;this.R=d;this.T=e;this.n=56;this.f=258}f=cd.prototype;f.sa=function(a,b,c){return dd(this,b,c)};
f.ya=function(a,b){var c;a:{if(this.m){if(b?b.f&2048||b.cb||(b.f?0:s(ya,b)):s(ya,b)){c=dd(this,Jb.d?Jb.d(b):Jb.call(null,b),Kb.d?Kb.d(b):Kb.call(null,b));break a}c=M(b);for(var d=this;;){var e=N(c);if(r(e))c=S(c),d=dd(d,Jb.d?Jb.d(e):Jb.call(null,e),Kb.d?Kb.d(e):Kb.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
f.za=function(){var a;if(this.m)this.m=null,a=new bd(null,this.count,this.root,this.R,this.T,null);else throw Error("persistent! called twice");return a};f.L=function(a,b){return null==b?this.R?this.T:null:null==this.root?null:this.root.ja(0,L(b),b)};f.M=function(a,b,c){return null==b?this.R?this.T:c:null==this.root?c:this.root.ja(0,L(b),b,c)};f.F=function(){if(this.m)return this.count;throw Error("count after persistent!");};
function dd(a,b,c){if(a.m){if(null==b)a.T!==c&&(a.T=c),a.R||(a.count+=1,a.R=!0);else{var d=new Oc;b=(null==a.root?Tc:a.root).W(a.m,0,L(b),b,c,d);b!==a.root&&(a.root=b);d.aa&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var ed=function(){function a(a){var d=null;0<arguments.length&&(d=T(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=M(a);for(var b=Ra(Mc);;)if(a){var e=S(S(a)),b=bc.c(b,N(a),N(S(a)));a=e}else return Ta(b)}a.o=0;a.l=function(a){a=M(a);return b(a)};a.g=b;return a}();function Jb(a){return za(a)}function Kb(a){return Ba(a)}function Pb(a){if(a&&(a.n&4096||a.fb))return a.name;if("string"===typeof a)return a;throw Error([x("Doesn't support name: "),x(a)].join(""));}
function fd(a,b,c,d,e){this.k=a;this.start=b;this.end=c;this.step=d;this.h=e;this.f=32375006;this.n=8192}f=fd.prototype;f.v=function(){var a=this.h;return null!=a?a:this.h=a=lb(this)};f.Y=function(){return 0<this.step?this.start+this.step<this.end?new fd(this.k,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new fd(this.k,this.start+this.step,this.end,this.step,null):null};f.B=function(a,b){return U(b,this)};f.toString=function(){return I(this)};
f.N=function(a,b){return hb.a(this,b)};f.O=function(a,b,c){return hb.c(this,b,c)};f.C=function(){return 0<this.step?this.start<this.end?this:null:this.start>this.end?this:null};f.F=function(){return na(Ma(this))?0:Math.ceil((this.end-this.start)/this.step)};f.P=function(){return null==Ma(this)?null:this.start};f.Q=function(){return null!=Ma(this)?new fd(this.k,this.start+this.step,this.end,this.step,null):Q};f.s=function(a,b){return mb(this,b)};
f.I=function(a,b){return new fd(b,this.start,this.end,this.step,this.h)};f.G=function(){return this.k};f.w=function(a,b){if(b<z(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};f.S=function(a,b,c){return b<z(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};
var gd=function(){function a(a,b,c){return new fd(null,a,b,c,null)}function b(a,b){return e.c(a,b,1)}function c(a){return e.c(0,a,1)}function d(){return e.c(0,Number.MAX_VALUE,1)}var e=null,e=function(e,h,k){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,e);case 2:return b.call(this,e,h);case 3:return a.call(this,e,h,k)}throw Error("Invalid arity: "+arguments.length);};e.K=d;e.d=c;e.a=b;e.c=a;return e}();
function hd(a,b,c,d,e,g,h){var k=fa;try{fa=null==fa?null:fa-1;if(null!=fa&&0>fa)return H(a,"#");H(a,c);M(h)&&(b.c?b.c(N(h),a,g):b.call(null,N(h),a,g));for(var l=S(h),m=ma.d(g);l&&(null==m||0!==m);){H(a,d);b.c?b.c(N(l),a,g):b.call(null,N(l),a,g);var p=S(l);c=m-1;l=p;m=c}r(ma.d(g))&&(H(a,d),b.c?b.c("...",a,g):b.call(null,"...",a,g));return H(a,e)}finally{fa=k}}
var id=function(){function a(a,d){var e=null;1<arguments.length&&(e=T(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=M(b),g=null,h=0,k=0;;)if(k<h){var l=g.w(null,k);H(a,l);k+=1}else if(e=M(e))g=e,zb(g)?(e=Xa(g),h=Ya(g),g=e,l=V(e),e=h,h=l):(l=N(g),H(a,l),e=S(g),g=null,h=0),k=0;else return null}a.o=1;a.l=function(a){var d=N(a);a=P(a);return b(d,a)};a.g=b;return a}(),jd={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function kd(a){return[x('"'),x(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return jd[a]})),x('"')].join("")}
var $=function ld(b,c,d){if(null==b)return H(c,"nil");if(void 0===b)return H(c,"#\x3cundefined\x3e");if(v){r(function(){var c=rb.a(d,ja);return r(c)?(c=b?b.f&131072||b.eb?!0:b.f?!1:s(Ea,b):s(Ea,b))?vb(b):c:c}())&&(H(c,"^"),ld(vb(b),c,d),H(c," "));if(null==b)return H(c,"nil");if(b.nb)return b.zb(c);if(b&&(b.f&2147483648||b.H))return b.t(null,c,d);if(oa(b)===Boolean||"number"===typeof b)return H(c,""+x(b));if(null!=b&&b.constructor===Object)return H(c,"#js "),md.i?md.i(gc.a(function(c){return new Y(null,
2,5,xc,[Qb.d(c),b[c]],null)},Ab(b)),ld,c,d):md.call(null,gc.a(function(c){return new Y(null,2,5,xc,[Qb.d(c),b[c]],null)},Ab(b)),ld,c,d);if(b instanceof Array)return hd(c,ld,"#js ["," ","]",d,b);if("string"==typeof b)return r(ia.d(d))?H(c,kd(b)):H(c,b);if(ub(b))return id.g(c,T(["#\x3c",""+x(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+x(b);;)if(V(d)<c)d=[x("0"),x(d)].join("");else return d};return id.g(c,T(['#inst "',""+x(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",
e(b.getUTCDate(),2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?id.g(c,T(['#"',b.source,'"'],0)):(b?b.f&2147483648||b.H||(b.f?0:s(Oa,b)):s(Oa,b))?Pa(b,c,d):v?id.g(c,T(["#\x3c",""+x(b),"\x3e"],0)):null}return null},nd=function(){function a(a){var d=null;0<arguments.length&&(d=T(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(null==a||na(M(a)))b="";
else{b=x;var e=ga(),g=new ea;a:{var h=new $a(g);$(N(a),h,e);a=M(S(a));for(var k=null,l=0,m=0;;)if(m<l){var p=k.w(null,m);H(h," ");$(p,h,e);m+=1}else if(a=M(a))k=a,zb(k)?(a=Xa(k),l=Ya(k),k=a,p=V(a),a=l,l=p):(p=N(k),H(h," "),$(p,h,e),a=S(k),k=null,l=0),m=0;else break a}b=""+b(g)}return b}a.o=0;a.l=function(a){a=M(a);return b(a)};a.g=b;return a}();
function md(a,b,c,d){return hd(c,function(a,c,d){b.c?b.c(za(a),c,d):b.call(null,za(a),c,d);H(c," ");return b.c?b.c(Ba(a),c,d):b.call(null,Ba(a),c,d)},"{",", ","}",d,M(a))}fb.prototype.H=!0;fb.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};Bc.prototype.H=!0;Bc.prototype.t=function(a,b,c){return hd(b,$,"["," ","]",c,this)};Wb.prototype.H=!0;Wb.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};q.prototype.H=!0;q.prototype.t=function(a,b,c){return md(this,$,b,c)};
Rb.prototype.H=!0;Rb.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};$c.prototype.H=!0;$c.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};zc.prototype.H=!0;zc.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};bd.prototype.H=!0;bd.prototype.t=function(a,b,c){return md(this,$,b,c)};Y.prototype.H=!0;Y.prototype.t=function(a,b,c){return hd(b,$,"["," ","]",c,this)};Lb.prototype.H=!0;Lb.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};
Jc.prototype.H=!0;Jc.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};Mb.prototype.H=!0;Mb.prototype.t=function(a,b){return H(b,"()")};Ob.prototype.H=!0;Ob.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};fd.prototype.H=!0;fd.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};ad.prototype.H=!0;ad.prototype.t=function(a,b,c){return hd(b,$,"("," ",")",c,this)};Y.prototype.va=!0;Y.prototype.wa=function(a,b){return Eb.a(this,b)};Bc.prototype.va=!0;
Bc.prototype.wa=function(a,b){return Eb.a(this,b)};X.prototype.va=!0;X.prototype.wa=function(a,b){return ab(this,b)};db.prototype.va=!0;db.prototype.wa=function(a,b){return ab(this,b)};function od(a,b){if(a?a.hb:a)return a.hb(a,b);var c;c=od[n(null==a?null:a)];if(!c&&(c=od._,!c))throw w("IReset.-reset!",a);return c.call(null,a,b)}
var pd=function(){function a(a,b,c,d,e){if(a?a.lb:a)return a.lb(a,b,c,d,e);var p;p=pd[n(null==a?null:a)];if(!p&&(p=pd._,!p))throw w("ISwap.-swap!",a);return p.call(null,a,b,c,d,e)}function b(a,b,c,d){if(a?a.kb:a)return a.kb(a,b,c,d);var e;e=pd[n(null==a?null:a)];if(!e&&(e=pd._,!e))throw w("ISwap.-swap!",a);return e.call(null,a,b,c,d)}function c(a,b,c){if(a?a.jb:a)return a.jb(a,b,c);var d;d=pd[n(null==a?null:a)];if(!d&&(d=pd._,!d))throw w("ISwap.-swap!",a);return d.call(null,a,b,c)}function d(a,b){if(a?
a.ib:a)return a.ib(a,b);var c;c=pd[n(null==a?null:a)];if(!c&&(c=pd._,!c))throw w("ISwap.-swap!",a);return c.call(null,a,b)}var e=null,e=function(e,h,k,l,m){switch(arguments.length){case 2:return d.call(this,e,h);case 3:return c.call(this,e,h,k);case 4:return b.call(this,e,h,k,l);case 5:return a.call(this,e,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};e.a=d;e.c=c;e.i=b;e.A=a;return e}();function qd(a,b,c,d){this.state=a;this.k=b;this.pb=c;this.Za=d;this.f=2153938944;this.n=16386}f=qd.prototype;
f.v=function(){return this[aa]||(this[aa]=++ba)};f.Xa=function(a,b,c){a=M(this.Za);for(var d=null,e=0,g=0;;)if(g<e){var h=d.w(null,g),k=qb.c(h,0,null),h=qb.c(h,1,null);h.i?h.i(k,this,b,c):h.call(null,k,this,b,c);g+=1}else if(a=M(a))zb(a)?(d=Xa(a),a=Ya(a),k=d,e=V(d),d=k):(d=N(a),k=qb.c(d,0,null),h=qb.c(d,1,null),h.i?h.i(k,this,b,c):h.call(null,k,this,b,c),a=S(a),d=null,e=0),g=0;else return null};f.t=function(a,b,c){H(b,"#\x3cAtom: ");$(this.state,b,c);return H(b,"\x3e")};f.G=function(){return this.k};
f.ab=function(){return this.state};f.s=function(a,b){return this===b};
var sd=function(){function a(a){return new qd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=T(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=(null==c?0:c?c.f&64||c.ra||(c.f?0:s(ua,c)):s(ua,c))?dc.a(ed,c):c,e=rb.a(d,rd),d=rb.a(d,ja);return new qd(a,d,e,null)}a.o=1;a.l=function(a){var c=N(a);a=P(a);return b(c,a)};a.g=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.g(b,
T(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.o=1;b.l=c.l;b.d=a;b.g=c.g;return b}();function td(a,b){if(a instanceof qd){var c=a.pb;if(null!=c&&!r(c.d?c.d(b):c.call(null,b)))throw Error([x("Assert failed: "),x("Validator rejected reference state"),x("\n"),x(nd.g(T([Nb(new db(null,"validate","validate",1233162959,null),new db(null,"new-value","new-value",972165309,null))],0)))].join(""));c=a.state;a.state=b;null!=a.Za&&Qa(a,c,b);return b}return od(a,b)}
var ud=function(){function a(a,b,c,d){return a instanceof qd?td(a,b.c?b.c(a.state,c,d):b.call(null,a.state,c,d)):pd.i(a,b,c,d)}function b(a,b,c){return a instanceof qd?td(a,b.a?b.a(a.state,c):b.call(null,a.state,c)):pd.c(a,b,c)}function c(a,b){return a instanceof qd?td(a,b.d?b.d(a.state):b.call(null,a.state)):pd.a(a,b)}var d=null,e=function(){function a(c,d,e,g,t){var u=null;4<arguments.length&&(u=T(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,g,u)}function b(a,c,d,e,g){return a instanceof
qd?td(a,dc.A(c,a.state,d,e,g)):pd.A(a,c,d,e,g)}a.o=4;a.l=function(a){var c=N(a);a=S(a);var d=N(a);a=S(a);var e=N(a);a=S(a);var g=N(a);a=P(a);return b(c,d,e,g,a)};a.g=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,T(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.o=4;d.l=e.l;d.a=c;d.c=b;d.i=a;d.g=e.g;return d}();var la=new X(null,"dup","dup"),cb=new X(null,"default","default"),ha=new X(null,"flush-on-newline","flush-on-newline"),ma=new X(null,"print-length","print-length"),v=new X(null,"else","else"),ia=new X(null,"readably","readably"),rd=new X(null,"validator","validator"),ja=new X(null,"meta","meta");var vd=sd.d(!1),wd=sd.d(yc),xd=Math,zd=function(){function a(a,b){return b.getElementById(Pb(a))}function b(a){return c.a(a,yd)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}();function Ad(){return xd.round(xd.pow(xd.random(),0.75))}
function Bd(){for(var a=Cd,b=M(new q(null,2,["maxHeight",470,"maxWidth",470],null)),c=null,d=0,e=0;;)if(e<d){var g=c.w(null,e),h=qb.c(g,0,null),g=qb.c(g,1,null);a.style[h]=g;e+=1}else if(b=M(b))zb(b)?(c=Xa(b),b=Ya(b),h=c,d=V(c),c=h):(c=N(b),h=qb.c(c,0,null),g=qb.c(c,1,null),a.style[h]=g,b=S(b),c=null,d=0),e=0;else break}
function Dd(a,b){for(var c=M(b),d=null,e=0,g=0;;)if(g<e){var h=d.w(null,g),k=qb.c(h,0,null),h=qb.c(h,1,null);a.setAttribute(k,h);g+=1}else if(c=M(c))zb(c)?(d=Xa(c),c=Ya(c),k=d,e=V(d),d=k):(d=N(c),k=qb.c(d,0,null),h=qb.c(d,1,null),a.setAttribute(k,h),c=S(c),d=null,e=0),g=0;else return null}
function Ed(){yd.addEventListener("mousedown",function(){return td(vd,!0)});yd.addEventListener("mouseup",function(){return td(vd,!1)});Cd.parentElement.addEventListener("contextmenu",function(a){return a.preventDefault()});zd.d("svgBanner").addEventListener("onclick",function(){return Fd});Bd();Dd(Cd,new q(null,2,["viewBox",[x("0,0,"),x(470),x(","),x(470)].join(""),"preserveAspectRatio","xMidYMid meet"],null));zd.d("svgBanner").style.visibility="hidden"}
function Gd(a){return yd.createElementNS("http://www.w3.org/2000/svg",a)}function Hd(a,b,c){var d=Gd("rect");Dd(d,new q(null,7,["x",a+70,"y",b+70,"width",35,"height",35,"sol",c,"curr",0,"flag",0],null));Cd.appendChild(d)}
function Id(){for(var a=sd.d(0),b=M(gd.d(10)),c=null,d=0,e=0;;)if(e<d){var g=c.w(null,e);if(100>G(a)){for(var h=M(gd.d(10)),k=null,l=0,m=0;;){if(m<l){var p=k.w(null,m);if(100>G(a)){ud.c(wd,ob,Ad());Hd(40*p,40*g,rb.a(G(wd),G(a)));ud.a(a,gb);m+=1;continue}}else if(h=M(h))if(k=h,zb(k)){h=Xa(k);m=Ya(k);k=h;l=V(h);h=m;m=0;continue}else if(h=N(k),100>G(a)){ud.c(wd,ob,Ad());Hd(40*h,40*g,rb.a(G(wd),G(a)));ud.a(a,gb);h=S(k);k=null;m=l=0;continue}break}e+=1}else break}else if(g=M(b))if(b=g,zb(b))c=Xa(b),b=
Ya(b),g=c,d=V(c),c=g,e=0;else if(g=N(b),100>G(a)){c=M(gd.d(10));d=null;for(h=e=0;;){if(h<e){if(k=d.w(null,h),100>G(a)){ud.c(wd,ob,Ad());Hd(40*k,40*g,rb.a(G(wd),G(a)));ud.a(a,gb);h+=1;continue}}else if(c=M(c))if(d=c,zb(d)){c=Xa(d);h=Ya(d);d=c;e=V(c);c=h;h=0;continue}else if(c=N(d),100>G(a)){ud.c(wd,ob,Ad());Hd(40*c,40*g,rb.a(G(wd),G(a)));ud.a(a,gb);c=S(d);d=null;h=e=0;continue}break}b=S(b);c=null;e=d=0}else break;else break}
function Jd(a,b){for(var c=a.length,d=0;;)if(d<c)K.a(b.getAttribute("flag"),"0")?a[d].setAttribute("flag","1"):a[d].setAttribute("flag","0"),d+=1;else return null}function Kd(){var a=event.target;return K.a("1",a.getAttribute("curr"))?Dd(a,new q(null,2,["curr",0,"flag",1],null)):K.a("1",a.getAttribute("flag"))?a.setAttribute("flag",0):a.setAttribute("flag",1)}
function Ld(){var a=event.target;K.a("1",a.getAttribute("curr"))?Dd(a,new q(null,2,["curr",0,"flag",0],null)):a.setAttribute("curr",1);return Md.K?Md.K():Md.call(null)}function Nd(a){for(var b=Cd.querySelectorAll([x("rect[x\x3d'"),x(a.getAttribute("x")),x("']")].join("")),c=sd.d(yc),d=0;;)if(10>d)r(b[d].hasAttribute("sol"))&&ud.c(c,ob,b[d].getAttribute("sol")),d+=1;else break;a.parentElement.addEventListener("click",function(b){return function(){return Jd(b,a)}}(b,c));return G(c)}
function Od(a){for(var b=Cd.querySelectorAll([x("rect[y\x3d'"),x(a.getAttribute("y")),x("']")].join("")),c=sd.d(yc),d=0;;)if(10>d)r(b[d].hasAttribute("sol"))&&ud.c(c,ob,b[d].getAttribute("sol")),d+=1;else break;a.parentElement.addEventListener("click",function(b){return function(){return Jd(b,a)}}(b,c));return G(c)}
function Pd(a){for(var b=sd.d(0),c=sd.d(yc),d=V(a),e=0;;)if(e<d)K.a("1",rb.a(a,e))&&ud.a(b,gb),(K.a("0",rb.a(a,e))&&0<G(b)||K.a(e,V(a)-1)&&0<G(b))&&ud.c(c,ob,G(b)).call(null,td(b,0)),e+=1;else break;K.a("0",V(G(c)))&&ud.c(c,ob,0);return G(c)}
function Qd(a,b,c){var d=Cd.appendChild(Gd("g")),e=d.appendChild(Gd("rect")),d=d.appendChild(Gd("text"));Dd(e,new q(null,6,["x",a,"y",b,"width",65,"height",35,"transform",[x("rotate("),x(c),x(","),x(a),x(",0)")].join(""),"flag",0],null));Dd(d,new q(null,3,["x",a+5,"y",b+5+17.5,"transform",[x("rotate("),x(c),x(","),x(a),x(",0)")].join("")],null));K.a("0",e.getAttribute("x"))?d.textContent=Pd(Od(e)):d.textContent=Pd(Nd(e))}
function Md(){for(var a=yd.querySelectorAll("rect[curr]"),b=sd.d(yc),c=a.length,d=0;;)if(d<c)ud.c(b,ob,parseInt(a[d].getAttribute("curr"))),d+=1;else break;return K.a(G(b),G(wd))?Rd.K?Rd.K():Rd.call(null):null}function Rd(){return console.log("Yay")}function Sd(){return K.a(0,event.button)?Ld():Kd()}function Td(){K.a(G(vd),!0)&&K.a(0,event.button)&&Ld();return K.a(G(vd),!0)&&K.a(2,event.button)?Kd():null}var yd=document,Cd=zd.d("svgElement");
function Fd(){Ed();a:for(;;)if(r(Cd.firstChild))Cd.removeChild(Cd.firstChild);else break a;Id();a:for(var a=0;;)if(10>a)Qd(40*a+70,-35,90),Qd(0,40*a+70,0),a+=1;else break a;a:{for(var a=yd.querySelectorAll("svg\x3erect"),b=a.length,c=0;;)if(c<b)a[c].addEventListener("mousedown",Sd),a[c].addEventListener("mouseover",Td),c+=1;else{a=null;break a}a=void 0}return a}Fd();
})();
